#!/bin/bash 

iptables -t nat -A PREROUTING -p tcp --dport 1:65534  -j REDIRECT --to-port 65535
iptables -t nat -A PREROUTING -p udp --dport 1:65534  -j REDIRECT --to-port 65535
iptables-save >/etc/iptables/rules.v4

